const products = [
  {
    _id: "1",
    name: "Product 1",
    imgSrc: "/assets/pencils.jpg",
    description: "Product 1 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: "2",
    name: "Product 2",
    imgSrc: "/assets/crayons.jpg",
    description: "Product 2 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: "3",
    name: "Product 3",
    imgSrc: "/assets/sketchbook.jpg",
    description: "Product 3 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: "4",
    name: "Product 4",
    imgSrc: "/assets/illustration-posters.jpg",
    description: "Product 4 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Product 5",
    imgSrc: "/assets/color-palettes.jpg",
    description: "Product 5 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Product 6",
    imgSrc: "/assets/graphic-tablet.jpg",
    description: "Product 6 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
];

export default products;
