const products = [
  {
    _id: "1",
    name: "Drawing Pencils",
    imgSrc: "/assets/pencils.jpg",
    description: "Product 1 Text Content",
    category: "",
    brand: "",
    price: 24.99,
    countInStock: 0,
    rating: 4,
    numReviews: 8,
  },
  {
    _id: "2",
    name: "Crayons",
    imgSrc: "/assets/crayons.jpg",
    description: "Product 2 Text Content",
    category: "",
    brand: "",
    price: 14.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "3",
    name: "Sketchbook",
    imgSrc: "/assets/sketchbook.jpg",
    description: "Product 3 Text Content",
    category: "",
    brand: "",
    price: 32.99,
    countInStock: 0,
    rating: 3,
    numReviews: 16,
  },
  {
    _id: "4",
    name: "Posters",
    imgSrc: "/assets/illustration-posters.jpg",
    description: "Product 4 Text Content",
    category: "",
    brand: "",
    price: 54.99,
    countInStock: 0,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Color Palettes",
    imgSrc: "/assets/color-palettes.jpg",
    description: "Product 5 Text Content",
    category: "",
    brand: "",
    price: 28.99,
    countInStock: 0,
    rating: 5,
    numReviews: 2,
  },
  {
    _id: "6",
    name: "Graphic Tablets",
    imgSrc: "/assets/graphic-tablet.jpg",
    description: "Product 6 Text Content",
    category: "",
    brand: "",
    price: 32.99,
    countInStock: 0,
    rating: 4,
    numReviews: 27,
  },
];

export default products;
